name: build ubuntu
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 1 * *"
    push:
        branches:
            - master
        paths:
            - "ubuntu/**"
jobs:
    push:
        name: "images:ubuntu_${{ matrix.tag }}"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                tag:
                    - "22.04"
                    - "24.04"
        steps:
            - uses: actions/checkout@v3
            - uses: docker/setup-qemu-action@v2
            - uses: docker/setup-buildx-action@v2
              with:
                buildkitd-flags: --debug
            - uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.REGISTRY_TOKEN }}
            - uses: docker/build-push-action@v4
              with:
                  context: ./ubuntu
                  file: ./ubuntu/${{ matrix.tag }}/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                        ghcr.io/${{ github.repository_owner }}/images:ubuntu_${{ matrix.tag }} 